In [2]:
import numpy as np
import pandas as pd

In [3]:
df  = pd.read_csv(r"C:\Users\24SRV\OneDrive\Desktop\brazilian_ecommerce_project\data\raw\olist_sellers_dataset.csv")
df.head(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [4]:
df.shape

(3095, 4)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [6]:
df["seller_id"].duplicated().sum()

0

In [7]:
df["seller_zip_code_prefix"].dtype

dtype('int64')

In [8]:
df["seller_zip_code_prefix"] = df["seller_zip_code_prefix"].astype(str).str.zfill(5)

In [9]:
df["seller_zip_code_prefix"].dtype

dtype('O')

In [10]:
df["seller_city"].unique()

array(['campinas', 'mogi guacu', 'rio de janeiro', 'sao paulo',
       'braganca paulista', 'brejao', 'penapolis', 'curitiba', 'anapolis',
       'itirapina', 'tubarao', 'lauro de freitas', 'imbituba', 'brasilia',
       'porto seguro', 'guaruja', 'tabatinga', 'salto', 'tres de maio',
       'belo horizonte', 'arapongas', 'sao bernardo do campo', 'tatui',
       'garopaba', 'camanducaia', 'tupa', 'guarulhos',
       'sao jose dos pinhais', 'sao ludgero', 'sao jose', 'piracicaba',
       'porto alegre', 'congonhal', 'santo andre', 'osasco', 'valinhos',
       'joinville', 'saquarema', 'barra velha', 'petropolis',
       'santo antonio da patrulha', 'ponta grossa', 'santana de parnaiba',
       'sao carlos', 'ibitinga', 'barueri', 'caxias do sul', 'araguari',
       'contagem', 'jaragua do sul', 'lages - sc', 'bento goncalves',
       'catanduva', 'ribeirao pires', 'jaboticabal', 'echapora', 'cotia',
       'rio do sul', 'sorocaba', 'pradopolis', 'itaborai', 'mirassol',
       'birigui', 'assis', 'jaguariuna', 'araraquara', 'macae',
       'rio claro', 'londrina', 'ribeirao preto', 'tres coracoes',
       'nhandeara', 'orleans', 'cuiaba', 'formosa do oeste', 'santos',
       'santa terezinha de goias', 'arvorezinha', 'guiricema', 'caruaru',
       'franca', 'salvador', 'diadema', 'itaquaquecetuba',
       'lencois paulista', 'carapicuiba', 'uruacu', 'itajai', 'loanda',
       'maringa', 'ferraz de vasconcelos', 'limeira', 'claudio',
       'niteroi', 'osvaldo cruz', 'sao goncalo', 'jaciara',
       'balenario camboriu', 'timbo', 'jacutinga', 'fortaleza',
       'ferraz de  vasconcelos', 'mirandopolis', 'bauru', 'jacarei',
       'itu', 'laranjeiras do sul', 'videira', 'florianopolis',
       'itapecerica da serra', 'mamanguape', 'ponte nova', 'goioere',
       'pederneiras', 'itapevi', 'goiania', 'campina grande',
       'estancia velha', 'resende', 'maua', 'caratinga', 'auriflama/sp',
       'cafelandia', 'uba', 'sao paulo / sao paulo',
       'sao jose do rio preto', 'porto ferreira', 'tres coroas',
       'blumenau', 'mogi das cruzes', 'jaci', 'laranjal paulista',
       'americana', 'sertanopolis', 'apucarana', 'colombo',
       'vicente de carvalho', 'mesquita', 'sao pauo', 'cascavel',
       'fazenda rio grande', 'taboao da serra', 'sao jose dos campos',
       'toledo', 'marechal candido rondon', 'jundiai', 'mandirituba',
       'suzano', 'vespasiano', 'santa rosa', 'sao joaquim da barra',
       'santo antonio de posse', 'uruguaiana', 'campanha', 'piracanjuba',
       'concordia', 'santa rita do sapucai', 'barretos', 'indaiatuba',
       'nilopolis', 'pompeia', 'barro alto', 'são paulo', 'praia grande',
       'luiz alves', 'brusque', 'criciuma', 'jales', 'atibaia',
       'rio branco', 'barra mansa', 'marilia', 'bahia', 'taubate',
       'cascavael', 'monteiro lobato', 'viana', 'paraiba do sul',
       'mococa', 'sao roque', 'passos', 'francisco beltrao', 'tocantins',
       'porto belo', 'nova iguacu', 'icara', 'lajeado', 'horizontina',
       'votorantim', 'campo bom', 'monte alto', 'fernandopolis',
       'pedreira', 'poa', 'divinopolis', 'santa barbara d´oeste',
       'canoas', 'mombuca', 'sete lagoas', 'campo do meio',
       'cordeiropolis', 'uberlandia', 'santa barbara d oeste',
       'volta redonda', '04482255', 'aracatuba', 'monte siao', 'garuva',
       'bonfinopolis de minas', 'cosmopolis', 'pocos de caldas',
       'artur nogueira', 'joao pessoa', 'dois corregos', 'araquari',
       'novo hamburgo, rio grande do sul, brasil', 'floranopolis',
       'sumare', 'guaira', 'cachoeiro de itapemirim', 'serrana',
       'rolandia', 'congonhas', 'sao  jose dos pinhais', 'boituva',
       'mairipora', 'guaimbe', 'parai', 'aperibe', 'jaguaruna',
       'vila velha', 'juiz de fora', 'fronteira', 'novo horizonte',
       'pilar do sul', 'itajobi', 'cariacica / es', 'prados', 'mucambo',
       'montes claros', 'vicosa', 'porto velho', 'sao jose do rio pardo',
       'pato branco', 'sao joao del rei', 'presidente prudente',
       'paracambi', 'serra negra', 'sao caetano do sul', 'bom jardim',
       'serra redonda', 'sao francisco do sul', 'betim', 'imbituva',
       'guaratuba', 'teresina', "sao miguel d'oeste", 'california',
       'japira', 'foz do iguacu', 'nova friburgo', 'itau de minas',
       'oliveira', 'sabara', 'pedrinhas paulista', 'votuporanga',
       'holambra', 'ararangua', 'pinhais', 'pato bragado', 'carazinho',
       'arinos', 'sao pedro', 'lages', 'ampere', 'itauna', 'mogi mirim',
       'curitibanos', 'brasilia df', 'mogi das cruses', 'hortolandia',
       'ipatinga', 'laguna', 'dores de campos', 'sao paulo - sp',
       'araras', 'divisa nova', 'igaracu do tiete', 'pitangueiras',
       'campo grande', 'garca', 'presidente epitacio', 'sbc/sp',
       "arraial d'ajuda (porto seguro)", 'pacatuba', 'formosa',
       'borda da mata', 'ubatuba', 'entre rios do oeste', 'formiga',
       'venancio aires', 'navegantes', 'cruzeiro', 'santa maria',
       'muriae', 'santo andre/sao paulo', 'ipe', 'messias targino',
       'varginha', 'botucatu', 'domingos martins', 'uberaba',
       'coronel fabriciano', 'cachoeirinha', 's jose do rio preto',
       'taruma', 'pirassununga', 'aruja', 'sp / sp', 'angra dos reis',
       'juzeiro do norte', 'laurentino', 'flores da cunha', 'montenegro',
       'pedregulho', 'novo hamburgo', 'torres', 'aracaju',
       'santa catarina', 'joao pinheiro', 'bady bassitt', 'sinop',
       'guarapuava', 'araucaria', 'vitoria', 'batatais', 'lagoa santa',
       'chapeco', 'umuarama', 'belford roxo', 'cariacica',
       'monte alegre do sul', 'sp', 'lagoa da prata', 'rolante',
       'teresopolis', 'itaporanga', 'campo largo', 'sao joao de meriti',
       'maua/sao paulo', 'bom jesus dos perdoes', 'brotas', 'irece',
       'coxim', 'jau', 'conselheiro lafaiete', 'amparo',
       'sao miguel do oeste', 'gaspar', 'rio bonito', 'mandaguari',
       'vargem grande paulista', 'conchal', 'cambe', 'marialva',
       'alfenas', 'balneario camboriu', 'palhoca', 'sao bernardo do capo',
       'guara', 'colatina', 'franco da rocha', 'lambari',
       'mogi das cruzes / sp', 'treze tilias',
       'rio de janeiro \\rio de janeiro', 'paulo lopes', 'santa cecilia',
       'braco do norte', 'floresta', 'farroupilha', 'castro', 'luziania',
       'joao monlevade', 'pelotas', 'sao bento', 'campos dos goytacazes',
       'ouro fino', 'sao jose dos pinhas', 'tiete', 'viamao', 'janauba',
       'capivari', 'santa terezinha de itaipu', 'igrejinha',
       'sao bento do sul', 'duque de caxias', 'araxa', 'canoinhas',
       'recife', 'barbacena/ minas gerais', 'vera cruz', 'parnamirim',
       'santo angelo', 'paincandu', 'tres rios', 'tanabi',
       'portoferreira', 'itatiba', 'sarandi', 'cravinhos', 'morrinhos',
       'bebedouro', 'almirante tamandare', 'bertioga', 'natal',
       'belo horizont', 'ivoti', 'andira-pr', 'cerqueira cesar',
       'marapoama', 'imigrante', 'mairinque', 'sao paulo sp',
       'rio de janeiro / rio de janeiro', 'andradas', 'sando andre',
       'nova odessa', 'paulinia', 'extrema', 'olimpia',
       'angra dos reis rj', 'ronda alta', 'sao  paulo', 'sao vicente',
       'pinhais/pr', 'portao', 'registro', 'ao bernardo do campo',
       'carmo do cajuru', 'embu das artes', 'fernando prestes',
       'castro pires', 'vargem grande do sul', 'campina das missoes',
       'sao pedro da aldeia', 'miguelopolis', 'itapui', 'sbc', 'neopolis',
       'mineiros do tiete', 'varzea paulista', 'nova lima', 'barbacena',
       'caieiras', 'buritama', 'erechim', 'itapetininga', 'pinhalzinho',
       'descalvado', 'pitanga', 'bage', 'taio', "santa barbara d'oeste",
       'patos de minas', 'garulhos', 'jarinu', 'nova petropolis',
       'ribeirao preto / sao paulo', 'camboriu', 'nova trento',
       'sao luis', 'sao jose do rio pret', 'eusebio', 'itaipulandia',
       'ipira', 'campo magro', 'tiradentes', 'sao paluo', 'baependi',
       'embu guacu', 'paraiso do sul', 'aparecida', 'cataguases',
       'bariri', 'abadia de goias', 'alambari', 'ji parana', 'vassouras',
       'lorena', 'rodeio', 'louveira', 'guanhaes',
       'santo antonio de padua', 'presidente getulio', 'campos novos',
       'eunapolis', 'engenheiro coelho', 'rio das pedras',
       'afonso claudio', 'carapicuiba / sao paulo', 'centro', 'parana',
       'indaial', 'bombinhas', 'orlandia', 'itapeva', 'sao sebastiao',
       'macatuba', 'sao joao da boa vista', 'teixeira soares',
       'mandaguacu', 'rio do oeste', 'vendas@creditparts.com.br',
       'armacao dos buzios', 'mateus leme', 'sao paulop',
       'campo limpo paulista', 'socorro', 'serra', 'bocaiuva do sul',
       'ilheus', 'imbe', 'soledade', 'cajamar', 'rio negrinho',
       'clementina', 'francisco morato', 'rio grande', 'xaxim', 'manaus',
       'terra boa', 'minas gerais', 'avare', 'ibirite',
       'santa maria da serra', 'auriflama', 'condor', 'ibia', 'guanambi',
       'caucaia', 'cordilheira alta', 'carmo da mata', 'ouro preto',
       'pedro leopoldo', 'santa rosa de viterbo', 'xanxere',
       'alvares machado', 'scao jose do rio pardo', 'ribeirao das neves',
       'medianeira', 'massaranduba', 'cornelio procopio', 'pirituba',
       'jambeiro', 'sao leopoldo', 'aguas claras df', 'ribeirao pretp',
       'cianorte', 'feira de santana', 'cachoeira do sul', 'guariba',
       'sao sebastiao da grama/sp', 'dracena', 'ourinhos',
       'robeirao preto', 'cacador', 'gama', 'queimados', 'cananeia',
       'presidente bernardes', 'pinhalao', 'sombrio', 'campo mourao',
       'ilicinea', 'itabira', 'barrinha', 'jussara', 'uniao da vitoria',
       'triunfo', 'santa cruz do sul', 'colorado', 'itapema', 'sapiranga',
       'paranavai', 'alvorada', 'ipaussu', 'rio verde', 'mage',
       'tabao da serra', 'bofete', 'picarras', 'marica', 'jaragua',
       'governador valadares', 'rio de janeiro, rio de janeiro, brasil',
       'pouso alegre', 'timoteo', 'muqui', 'ipua', 'jacarei / sao paulo',
       'varzea alegre', 'guaratingueta', 'tambau', 'irati',
       'riberao preto', 'aparecida de goiania', 'bandeirantes',
       'vitoria de santo antao', 'palotina', 'leme'], dtype=object)

In [11]:
df[df["seller_city"].str.contains(r"[/\-]", na=False)][
    ["seller_city", "seller_state"]
]

                          seller_city seller_state
78                         lages - sc           SC
237                      auriflama/sp           SP
246             sao paulo / sao paulo           SP
622                    cariacica / es           ES
826                    sao paulo - sp           SP
869                            sbc/sp           SP
945             santo andre/sao paulo           SP
1004                          sp / sp           SP
1159                   maua/sao paulo           SP
1337             mogi das cruzes / sp           SP
1447          barbacena/ minas gerais           MG
1580                   sao paulo - sp           SP
1610                        andira-pr           PR
1649  rio de janeiro / rio de janeiro           RJ
1712                       pinhais/pr           PR
1920       ribeirao preto / sao paulo           SP
2162          carapicuiba / sao paulo           SP
2620        sao sebastiao da grama/sp           SP
2946                   sao paulo - sp           SP
3015              jacarei / sao paulo           SP

In [12]:
df["seller_city"][78].split("-")

['lages ', ' sc']

In [13]:
df["seller_city"][78].split("-")[0]

'lages '

In [14]:
df["seller_city"][78].split("-")[0].strip()

'lages'

In [15]:
df["seller_city"] = (df["seller_city"].str.split(r"[/\-]").str[0].str.strip())

In [16]:
df[df["seller_city"].str.contains(r"[/\-]", na=False)][
    ["seller_city", "seller_state"]
]

Empty DataFrame
Columns: [seller_city, seller_state]
Index: []

In [17]:
df[df["seller_city"].str.contains(r"[/\-]", na=False)]

Empty DataFrame
Columns: [seller_id, seller_zip_code_prefix, seller_city, seller_state]
Index: []

In [18]:
df[df["seller_city"].str.contains(r"@|\d")]

,seller_id,seller_zip_code_prefix,seller_city,seller_state
517,ceb7b4fb9401cd378de7886317ad1b47,22790,04482255,RJ
2258,4b5f66b7adcf57f1ecc0d3c07dd6b177,87025,vendas@creditparts.com.br,PR

In [19]:
import numpy as np

df.loc[
    df["seller_city"].str.contains(r"@|\d", na=False),
    "seller_city"
] = np.nan

In [21]:
import unicodedata
df["seller_city"] = df["seller_city"].apply(lambda city:"".join(
    c for c in unicodedata.normalize("NFKD",city)
    if not unicodedata.combining(c)
).strip().lower()
if pd.notna(city) else city
)

In [22]:
df.duplicated().sum()

0

In [23]:
df["seller_state"].unique()

array(['SP', 'RJ', 'PE', 'PR', 'GO', 'SC', 'BA', 'DF', 'RS', 'MG', 'RN',
       'MT', 'CE', 'PB', 'AC', 'ES', 'RO', 'PI', 'MS', 'SE', 'MA', 'AM',
       'PA'], dtype=object)

In [24]:
df.to_csv("../data/cleaned/sellers_cleaned.csv" , index=False)